name: b3-comment
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            [Click here](https://b3-new.careevolution.com/#!/create?repo=Consumers&number={{id}}) to create a B3 instance for this pull request. (You can safely delete this comment if you do not want a B3 instance.)
